### ISSUE TITLE
Add any valid pull request.

### ISSUE THREAD

**Issue by tausiq2003** [tausiq2003/HACKTOBERFEST2021-CONTRIBUTION#1]
Read the `readme.md` for more and contribute according to that otherwise I will not accept and pull requests will marked as invalid.

**Comment by tausiq2003** [comment]
Happy Hacking.

**Comment by Siddhesh4501** [comment]
Hey I add Unit Converter using python please merge it. Thank You.

**Comment by nkhandelwal07** [comment]
Is it allowed to create another solution in python if one already exists in a different language? Thanks.

**Comment by tausiq2003** [comment]
sorry I have to close the repo
